apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance 
  namespace: openshift-logging
spec:
  outputs:
   - name: app-logs
     type: kafka
     url: tcp://my-cluster-kafka-bootstrap.amq.svc:9092/app-topic
   - name: infra-logs
     type: kafka
     url: tcp://my-cluster-kafka-bootstrap.amq.svc:9092/infra-topic
   - name: audit-logs
     type: kafka
     url: tcp://my-cluster-kafka-bootstrap.amq.svc:9092/audit-topic
  pipelines:
   - name: app-topic
     inputRefs:
     - application
     outputRefs:
     - app-logs
   - name: infra-topic
     inputRefs:
     - infrastructure
     outputRefs:
     - infra-logs
   - name: audit-topic
     inputRefs:
     - audit
     outputRefs:
     - audit-logs
     - default
