---
- name: Deploy Kafka cluster
  k8s:
    state: present
    namespace: "{{ amq_namespace }}"
    definition: "{{ lookup('file', item ) }}"
  with_items:
    - 01-kafka-namespace.yaml
    - 02-kafka-og.yaml
    - 03-kafka-sub-streams.yaml
    - 04-kafka-cluster.yaml

# TODO
# Wait and Check if all resources are ready

- name: Create Kafka topics 
  k8s:
    state: present
    namespace: "{{ amq_namespace }}"
    definition: "{{ lookup('file', item ) }}"
  with_items:
    - 05-kafka-topics.yaml

- name: Create a logging instance 
  k8s:
    state: present
    namespace: "{{ amq_namespace }}"
    definition: "{{ lookup('file', item ) }}"
  with_items:
    - 11-cr-cluster-logging.yaml

# TODO 
# The next command is ugly as hell, I wonder if there's a better module for this

- name: Create the kafka - fluentd secret
  command: oc -n amq get secret my-cluster-cluster-ca-cert -o jsonpath='{.data.ca\.crt}' | base64 -d > ca.crt ; oc create secret generic kafka-fluent --from-file=ca-bundle.crt=ca.crt  -n openshift-logging

- name: Retrieve the secret
  openshift_raw:
    api: v1
    kind: Secret
    name: my-cluster-cluster-ca-cert
    namespace: amq
  register: mysecret


- name: Deploy Cluster log forwarder
  k8s:
    state: present
    namespace: "{{ amq_namespace }}"
    definition: "{{ lookup('file', 'clusterforwarder.yaml' ) }}"
  with_items:
    - 13-cr-logforwarding-to-kafka-topics.yaml

# TODO
# Wait and Check if all resources are ready
